checkpoints:
  save_dir: "./checkpoints/trans_2/"
  load_path: "./checkpoints/trans_2/model_TransModel.pkl"

model:
  params:
    feature_dim: 1280
    encoder:
      features:
        width_mult: 1

loss:
  id_loss:
    weight: 1
  tri_loss:
    weight: 1
    delta: 0.5

cuda:
  id: 0

modes:
  train:
    epoch: 10000
    lr: 0.0001
    gamma: 0.99
    train_num_workers: 6
    eval_num_workers: 6
    train_batch_id_size: 32
    eval_batch_id_size: 32
    switch_step:
      - 400
      - 100
    eval_epoch: 5
    report_step: 100
    save_step: 2000
    data_dir: "./data/datasets/"
    domain_datasets:
      source:
        - "cuhk02"
        - "cuhk03"
        - "dukemtmcreid"
        - "market1501"
      target:
        - "viper"
        - "prid"
        - "grid"
        - "ilids"
    timestamp: false

  resume:
    epoch: 10000
    lr: 0.0001
    gamma: 0.99
    train_num_workers: 6
    eval_num_workers: 6
    train_batch_id_size: 32
    eval_batch_id_size: 32
    switch_step:
      - 400
      - 100
    eval_epoch: 5
    report_step: 100
    save_step: 2000
    data_dir: "./data/datasets/"
    domain_datasets:
      source:
        - "cuhk02"
        - "cuhk03"
        - "dukemtmcreid"
        - "market1501"
      target:
        - "viper"
        - "prid"
        - "grid"
        - "ilids"
    timestamp: false

  eval:
    eval_num_workers: 4
    eval_batch_size: 32
    data_dir: "./data/datasets/"
    domain_datasets:
      target:
        - "viper"
        - "prid"
        - "grid"
        - "ilids"
    timestamp: false
